name: CI
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:

    debug:
        runs-on: ubuntu-latest
        steps:
            - name: Dump context
              env:
                  GITHUB_CONTEXT: ${{ toJson(github) }}
              run: echo "$GITHUB_CONTEXT"

    changedfiles:
        runs-on: ubuntu-latest
        outputs:
            all: ${{ steps.changes.outputs.all }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Get Changed files
              id: changes
              run: |
                if [ "${{ github.event_name }}" = "pull_request" ]; then
                  echo "Pull Request Changes"
                  echo "all=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)" >> $GITHUB_OUTPUT
                  echo "GITHUB_OUTPUT = $GITHUB_OUTPUT"
                elif [ ${{ github.ref == 'refs/heads/main' }} ]; then
                  echo "Merge to main changes"
                  if [ "${{ github.event.before }}" != "0000000000000000000000000000000000000000" ]; then
                     echo "all=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.before }} ${{ github.sha }} | xargs)" >> $GITHUB_OUTPUT
                  else
                     echo "This is the first commit"
                  fi
                fi

    build:
        needs: changedfiles
        runs-on: ubuntu-latest
        steps:
            - name: echo changed files
              run: echo "${{ needs.changedfiles.outputs.all }}"
